title: Franco Palenque
logo: .logo {
  width: 150px; /* Adjust size as needed */
  height: 150px; /* Adjust size as needed */
  border-radius: 50%; /* Makes the image circular */
  object-fit: cover; /* Ensures the image fits well inside the circle */
}
theme: jekyll-theme-minimal
