title: Franco Palenque
social:
  - label: "Tableau Public"
    icon: "fas fa-chart-bar"
    url: "https://public.tableau.com/app/profile/franco.palenque.valdez/vizzes"
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/Francopalval"
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/francopalenque/"
theme: jekyll-theme-minimal
