title: Franco Palenque
logo: assets/foto_cv_circle.png
theme: minima

# Custom links
social_links:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/francopalenque"
    icon: "fab fa-linkedin"
  - name: "Tableau Visualizations"
    url: "https://public.tableau.com/profile/tu_usuario"
    icon: "fas fa-chart-bar"
