title: Franco Palenque
description: >
  Connect with me: 
  [Tableau Public](https://public.tableau.com/app/profile/franco.palenque.valdez/vizzes) |
  [GitHub](https://github.com/Francopalval) |
  [LinkedIn](https://www.linkedin.com/in/francopalenque/)
theme: jekyll-theme-minimal
